### ISSUE TITLE
Can you show how you created the encrypted resource?

### ISSUE THREAD

**Issue by richp582** [brminnick/AzureMediaServicesSampleApp#5]
I've been following: https://github.com/Azure-Samples/media-services-v3-dotnet-tutorials to create an AES encrypted resource.  I've then used the token it gives me and try to load the video with the HLS endpoint (format=m3u8-aapl) and it doesn't work.

I'm sure I'm missing something so I'm hoping that you could give me a quick rundown on creating the encrypted video that you're using in your sample.

Thanks!!

**Comment by TheCodeTraveler** [comment]
Hi Rich,

Are you adding the Token to the header?

Here's an example in the sample app: https://github.com/brminnick/AzureMediaServicesSampleApp/blob/fc10f2265d5d757b16522a81bcda3658bb53d0da/AzureMediaServicesSampleApp/App.cs#L11

**Comment by richp582** [comment]
Yep!  I saw that part, but I meant the other side... where you took an asset and encrypted it.

Thanks for the fast response!

**Comment by TheCodeTraveler** [comment]
I'm not sure. I haven't created an encrypted video stream; I've only consumed them from the client side.

To ensure the client-side code is working, I use the existing samples on the [Azure Media Player](https://ampdemo.azureedge.net/azuremediaplayer.html) site.

**Comment by richp582** [comment]
Ahhh ok understood.  Thanks for the help!
